Users/urls.py
# define urls for the users app
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns =[
# Home page for users
	url(r'^addClient/',views.addClient,name='addClient'),
	url(r'^addPersonnel/',views.addPersonnel,name='addPersonnel'),
	url(r'^register/',views.Register,name="register"),
	url(r'^logout/',views.Logout,name="logout"),
	url(r'^login/',login,{'template_name':'users/login.html'},name='login'),
	url(r'^not_authorised/',views.not_authorised,name='not_authorised')
]

proj_track/urls.py
from django.conf.urls import url,include
from django.contrib import admin
# from rest_framework_jwt.views import obtain_jwt_token


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('projects.urls',namespace='projects')),
    url(r'^users/',include('Users.urls',namespace='users')),
    url(r'^api/projects/',include('projects.api.urls',namespace='projects-api')),
    url(r'^api/users/',include('Users.api.urls',namespace='users-api')),
    # url(r'^api-token-auth/',obtain_jwt_token),
]

projects/api/urls.py
from django.conf.urls import url
from django.contrib import admin
from projects.api.views import *

from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns=[
   # url(r'^$',ProjectListAPIView.as_view(), name ='list'),
   url(r'^$',ProjectList.as_view()),
   url(r'^logs/$',LogList.as_view()),
   url(r'^notifs/$',Notifications.as_view()),
   # url(r'^$',ProjectList.as_view()),
   url(r'^(?P<pk>\d+)/$',ProjectDetail.as_view()),
   url(r'^update/(?P<pk>\d+)/$',UpdateProjectProgess.as_view()),
   url(r'^create/(?P<pk>\d+)/$',CreateProjectCLient.as_view()),
   url(r'^viewTask/(?P<pk>\d+)/(?P<actv_id>\d+)/$',TaskList.as_view()),
   url(r'^viewPersonnelTask/(?P<pk>\d+)/$',PersonnelTaskList.as_view()),
   url(r'^createTask/(?P<pk>\d+)/$',TaskSaveList.as_view()),
   url(r'^search/$',SearchList.as_view()),
   url(r'^verbs/$',VerbsList.as_view()),
 ]

urlpatterns = format_suffix_patterns(urlpatterns)

projects/urls.py
# Define the urls for the project
from django.conf.urls import url
from . import views,views_json

urlpatterns = [
	url(r'^$',views.index, name='index'),
	url(r'^project/add/',views.addProject,name='AddProject'),
	url(r'^project/(?P<project_id>\d+)/$',views.viewProject,name='viewProject'),
	url(r'^project/proceed/(?P<project_id>\d+)/$',views.Proceed,name='Proceed'),
	url(r'^project/search/$',views.Search,name='Search'),
	
]

projects/forms.py
# forms for the projects
from django import forms
from .models import Project

class ProjectForm(forms.ModelForm):
	class Meta:
		model = Project
		fields=['name','proj_id','revision','owner']

class SearchForm(forms.Form):
	text_input = forms.CharField(label='Search Projects',max_length=200)

projects/api/views.py
# #views.py
from projects.models import *
from projects.api.serializers import *
from Users.api.serializers import *
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.http import Http404

from rest_framework.decorators import api_view
from rest_framework.response import Response 
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView 
from projects.api.permissions import *
from rest_framework.authentication import SessionAuthentication, BasicAuthentication,TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.authtoken.views import ObtainAuthToken

import django_fanout as fanout

# fanout.publish('test','Test Publish')

# Serializer Functions 

class ProjectList(APIView):
	""" 
	List all Projects
	
	"""
	permission_classes = (IsAuthenticated,)
	authentication_classes = (TokenAuthentication,)
	def get(self,request,format=None):
		user = request.user.username
		try:
			c=Personnel.objects.get(email__iexact=user)
			queryset = Project.objects.all()
			serializer =ProjectSerializer(queryset,many = True)
			return Response(serializer.data)
		except ObjectDoesNotExist:
			try:
				client=Client.objects.get(email__iexact=user)
				queryset = Project.objects.filter(owner=client).order_by('-date')
				serializer =ProjectSerializer(queryset,many = True)
				return Response(serializer.data)
			except ObjectDoesNotExist:
				pass


class CreateProjectCLient(APIView):
	"""
	Create new projects  
	"""
	def post(self,request,pk,format=None):
		if int(pk) == 0:
			data = request.data
			client_data=data["client"]
			project_data=data["project"]
			serializer0 = ClientSerializers(data=client_data)

			if serializer0.is_valid():
				user = serializer0.save()
				project_data["owner"] = user.id
				serializer = ProjectSaveSerializer(data=project_data)
				if serializer.is_valid():
					project=serializer.save()
					Revision = project.revision
					stage = Activity.objects.get(level=1)
					Person = Personnel.objects.get(email__iexact=request.user.username)
					e=Logs(project=project,activity=stage,person=Person,proj_rev=Revision)
					e.save()
					return Response(serializer.data)
			else:
				return Response({"errors":serializer0.errors})
		elif int(pk)==1:
			client_data=data["client"]
			project_data=data["project"]
			project_data["owner"] = int(client_data.id)
			serializer = ProjectSaveSerializer(data=project_data)
			if serializer.is_valid():
				project=serializer.save()
				Revision = project.revision
				stage = Activity.objects.get(level=1)
				Person = Personnel.objects.get(email__iexact=request.user.username)
				e=Logs(project=project,activity=stage,person=Person,proj_rev=Revision)
				e.save()
				return Response(serializer.data)
			return Response(serializer.errors)

class ProjectDetail(APIView):
	"""
	Displays project details 
	"""
	permission_classes = (IsAuthenticated,)
	authentication_classes = (TokenAuthentication,BasicAuthentication)
	def get_object(self,pk):
		try:
			return Project.objects.get(pk=pk)
		except ObjectDoesNotExist:
			raise Http404

	def get(self,request,pk,format=None):
		
		project = self.get_object(pk)
		serializer = ProjectSerializer(project)
		Log_data=Logs.objects.filter(project=project).order_by('-date')

		serializer_2 = LogsDetailSerializer(Log_data,many=True)
		# Finding number of activities in process
		num_activ=Activity.objects.count() 

        # Start computing % completion
		prg_level=[]
		for elem in Log_data:
			log_id = int(elem.activity.id)
			stage = Activity.objects.get(level=log_id)
			prg_level.append(int(stage.level))   
		lev=(max(prg_level)/float(num_activ))*100.0

		# end computing % completion

		data ={"project":serializer.data,"percentage":lev,"logs":serializer_2.data}

		return Response(data)


	def put(self,request,format =None):
		serializer = ProjectSerializer(request.data)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data)
		return Response(serializer.errors)

class SearchList(APIView):
	"""
	Returns a list of items from the search query
	"""
	permission_classes = (IsAuthenticated,PersonnelPermission,)
	
	authentication_classes = (TokenAuthentication,BasicAuthentication)
	def post(self,request,format = None):
		search_term =  request.data["search_term"]
		projects=Project.objects.filter(name__icontains=search_term) | Project.objects.filter(proj_id__icontains=search_term)
		serializer=ProjectSerializer(projects,many=True)
		return Response(serializer.data)


class LogList(APIView):
	"""
	Display Project Logs 

	"""
	permission_classes = (IsAuthenticated,PersonnelPermission,)
	
	authentication_classes = (TokenAuthentication,)
	def get(self,request,format = None):
		active_projects= Project.objects.filter(status__icontains="In Progress")
		log_data =[]
		for projct in active_projects:
			task = Logs.objects.filter(project=projct).latest('date')
			serializer=LogsSerializer(task)
			log_data.append(serializer.data)
		return Response(log_data)


class Notifications(APIView):
	"""
	Display notifications in the respective project departments.
	"""
	permission_classes = (IsAuthenticated,PersonnelPermission,)

	authentication_classes = (TokenAuthentication,BasicAuthentication)

	def get(self,request,format = None):
		active_projects= Project.objects.filter(status__icontains="In Progress")
		mkt_log=[];proj_log=[];fab_log=[]
		eng_log=[];client_log=[]
		for projct in active_projects:
			task = Logs.objects.filter(project=projct).latest('date')
			task_level=int(task.activity.level)+1
			actv=Activity.objects.get(level=task_level)
			if actv.classification == 'Projects Department':
				activ = ActivitySerializer(actv)
				dat = activ.data
				dat["name"]=projct.name; dat["proj_id"]=projct.id;
				proj_log.append(dat)
			elif actv.classification == 'Marketing':
				activ = ActivitySerializer(actv)
				dat = activ.data
				dat["name"]=projct.name; dat["proj_id"]=projct.id;
				mkt_log.append(dat)
			elif actv.classification == 'Engineering':
				activ = ActivitySerializer(actv)
				dat = activ.data
				dat["name"]=projct.name; dat["proj_id"]=projct.id;
				eng_log.append(dat)
			elif actv.classification == 'Fabrication':
				activ = ActivitySerializer(actv)
				dat = activ.data
				dat["name"]=projct.name; dat["proj_id"]=projct.id;
				fab_log.append(dat)
			elif actv.classification == 'Client':
				activ = ActivitySerializer(actv)
				dat = activ.data
				dat["name"]=projct.name; dat["proj_id"]=projct.id;
				client_log.append(dat)	

		data = {"project_dept":proj_log,"marketing_dept":mkt_log,"Eng_dept":eng_log,"Fab_dept":fab_log,"client_dept":client_log}
		return Response(data)


class UpdateProjectProgess(APIView):
	"""
	 Takes project to next level  project details 

	"""

	permission_classes = (PersonnelPermission,)
	authentication_classes = (TokenAuthentication,BasicAuthentication)
	def get_object(self,pk):
		try:
			return Project.objects.get(pk=pk)
		except ObjectDoesNotExist:
			raise Http404

	def get(self,request,pk,format=None):
		
		project = self.get_object(pk)

		#  Updating data about a project 

		Person = Personnel.objects.get(email__iexact=request.user.username)
		Revision = project.revision
		log= Logs.objects.filter(project=project).latest('date')
		log_id =int(log.activity.id)
		stage = Activity.objects.get(level=log_id+1)
		e=Logs(project=project,activity=stage,person=Person,proj_rev=Revision)
		e.save()

		# Retrieving data  from updated project.

		serializer = ProjectSerializer(project)
		Log_data=Logs.objects.filter(project=project).order_by('-date')

		serializer_2 = LogsDetailSerializer(Log_data,many=True)
		# Finding number of activities in process
		num_activ=Activity.objects.count() 

        # Start computing % completion
		prg_level=[]
		for elem in Log_data:
			log_id = int(elem.activity.id)
			stage = Activity.objects.get(level=log_id)
			prg_level.append(int(stage.level))   
		lev=(max(prg_level)/float(num_activ))*100.0

		# end computing % completion

		data ={"project":serializer.data,"percentage":lev,"logs":serializer_2.data}

		return Response(data)


class TaskList(APIView):
	authentication_classes = (TokenAuthentication,BasicAuthentication)
	def get(self,request,pk,actv_id,format = None):
		pk = int(pk)
		try:
			queryset = Tasks.objects.filter(project=pk,activity=actv_id)
			serializer = TaskSerializer(queryset,many =True)
			return Response(serializer.data)
		except ObjectDoesNotExist:
			data ={}
			return Response(data)
		pass

class PersonnelTaskList(APIView):
	authentication_classes = (TokenAuthentication,BasicAuthentication)
	def get(self,request,pk,format = None):
		pk = int(pk)
		try:
			queryset = Tasks.objects.filter(person=pk,status=1) | Tasks.objects.filter(supervisor=pk,status=2)
			serializer = TaskSerializer(queryset,many =True)
			return Response(serializer.data)
		except ObjectDoesNotExist:
			data ={}
			return Response(data)
		pass

class VerbsList(APIView):
	permission_classes = (PersonnelPermission,)
	authentication_classes = (TokenAuthentication,BasicAuthentication)
	def get(self,request,format= None):
		queryset = DepartmentVerbs.objects.all()
		serializer = VerbsSerializer(queryset,many = True)
		return Response(serializer.data)

		
class TaskSaveList(APIView):
	permission_classes = (PersonnelPermission,)
	authentication_classes = (TokenAuthentication,BasicAuthentication)
	def get_object(self,pk):
		try:
			return Tasks.objects.get(pk=pk)
		except ObjectDoesNotExist:
			data = {};return Response(data)
		
	def post(self,request,pk,format = None):
		data = request.data
		data2 = []
		task =data["task_info"]
		comment = data["comment"]
		for elem in task:
			serializer = TaskSaveSerializer(data = elem)
			if serializer.is_valid():
				Task = serializer.save() 
				data2.append(serializer.data)
				comment['task'] = Task.id
				serializer0 = CommentSaveSerializer(data = comment)

projects/templates/projects/addProject.html
{% extends "projects/base.html" %}
{% load bootstrap3 %}
{% block content %}
<H2>Add a New Project</H2>
	<form action="{% url 'projects:AddProject' %}" method="POST">
		{% csrf_token %}
		{% bootstrap_form form %}
	{% buttons %}	
	<button class="btn btn-primary" name="Submit"> Add Project</button>
	{% endbuttons %}
	</form>
{% endblock content %}

projects/templates/projects/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">	
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">	
    {% bootstrap_css %}
    {% bootstrap_javascript %}
	<title>Project Tracking</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle= "collapse" data-target ="#navbar" aria-expanded="false" aria-controls ="navbar">
			</button> 
			<h2>ME-SSP Project Tracking </h2>	
			<a class="navbar-brand" href="{% url 'projects:index' %}">Home</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
					<li><a href="{% url 'users:logout' %}">Log Out</a></li>
				{% else %}
					<li><a href="{% url 'users:login' %}">Log In</a></li>
					<li><a href="{% url 'users:register' %}">Register</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>
<div class="container">
	<div>
		{% block content %}
		{% endblock content %}
	</div>
</div>

</body>
</html>

projects/templates/projects/client.html
{% extends "projects/base.html" %}

{% block content %}
	<p>Client:{{client.name }}</p>
	Contact Person {{client.contact_person_name}}
	</br>
	<ul class="list-group">
		{% for project in  projects %}
			<li class="list-group-item list-group-item-info"><a href="{% url 'projects:viewProject' project.id %}">{{project.name}} {{project.proj_id}} {{project.revision}}</a></li>
		{% endfor %}
	</ul>
	
{% endblock content %}

projects/templates/projects/index.html
{% extends "projects/base.html" %}
{% load bootstrap3 %}
{% block content %}
	<ul class="nav nav-pills">
	<li class="active"><a href="{% url 'users:addClient' %}">Create New Project</a></li>
	<li><a href="{% url 'users:addPersonnel' %}">Create New Personnel</a></li>
	<li >
	<form action="{% url 'projects:Search' %}" method="POST" >
		{% csrf_token %}
		{% bootstrap_form form layout='inline'%}
	</form>
	</li>
	</ul>
	<ul class="nav nav-tabs">
		<li class="active"><a data-toggle="tab" href="#recent">Recent</a></li>
		<li><a data-toggle="tab" href="#market">Marketing <span class="badge"> {{Mkt|length}}</span></a></li>
		<li><a data-toggle="tab" href="#proj">Projects Department <span class="badge">{{Prj|length}} </span></a></li>
		<li><a data-toggle="tab" href="#eng">Engineering <span class="badge">{{Eng|length}}</span> </a></li>
		<li><a data-toggle="tab" href="#fab">Fabrication <span class="badge">{{Fab|length}}</span> </a></li>
	</ul>
	<div class="tab-content">
		<div id="recent" class="tab-pane fade in active">
			<div class="list-group">
			{% for log in logs  %}
				<a href="{% url 'projects:viewProject' log.project.id %}" class="list-group-item  list-group-item-success">
					<b>{{log.activity}}</b>  {{log.date|date:'M d, Y H:i'}}
				<span class="badge">{{log.project.name}} {{log.project.proj_id}}{{log.proj_rev}}</span>
				</a>
			{% endfor %}
			</div>
		</div>
		<div id="market" class="tab-pane fade">
			{% for elm in Mkt %}
			    <a href="{% url 'projects:viewProject' elm.1.id %} "class="list-group-item  list-group-item-info">
				{{elm.0.activity}} <span class="badge">{{elm.1.name}} {{elm.1.proj_id}}</span>
				</a>
			{% endfor %}
		</div>
		<div id="proj" class="tab-pane fade">
		<div class="list-group">
			{% for elm in Prj %}
			   <a href="{% url 'projects:viewProject' elm.1.id %} "class="list-group-item  list-group-item-info">
				{{elm.0.activity}} <span class="badge">{{elm.1.name}} {{elm.1.proj_id}}</span>
				</a>
			{% endfor %}
		</div>
		</div>
		<div id="eng" class="tab-pane fade">
			{% for elm in Eng %}
				<a href="{% url 'projects:viewProject' elm.1.id %} "class="list-group-item  list-group-item-info">
				{{elm.0.activity}} <span class="badge">{{elm.1.name}} {{elm.1.proj_id}}</span>
				</a>
			{% endfor %}
		</div>
		<div id="fab" class="tab-pane fade">
			{% for elm in Fab %}
				<a href="{% url 'projects:viewProject' elm.1.id %}" class="list-group-item  list-group-item-info">
				{{elm.0.activity}} <span class="badge">{{elm.1.name}} {{elm.1.proj_id}}</span>
				</a>
			{% endfor %}
		</div>
	</div>

{% endblock content %}

projects/templates/projects/search.html
{% extends "projects/base.html" %}
{% load bootstrap3 %}
{% block content %}
<div class="panel panel-default">
	<div class="panel-heading">
	<h3>Showing Results for : {{search_term}}</h3>	
	</div>
	<div class="panel-body">
		{% for proj in projects %}
			<a href="{% url 'projects:viewProject' proj.id %}">
				<p>{{proj.name }} {{proj.proj_id}}</p>
			</a>
		{% endfor %}
	</div>
</div>


{% endblock content %}

projects/templates/projects/viewProject.html
{% extends "projects/base.html" %}

{% block content %}

The percentage is {{percentage}} .
<h3>{{Project.name}}</h3>
	<ul class="nav nav-tabs">
		<li class="active"><a data-toggle="tab" href="#progress">Progress</a></li>
		<li><a data-toggle="tab" href="#log">Event Logs</a></li>
	</ul>

	<div class="tab-content">
		<div id="progress" class="tab-pane fade in active">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h6>Project Progress</h6>	
				</div>
			<div class="panel-body">
				<div class="progress">
					<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valumax="100" style="width:{{percentage}}%">{{percentage}}%(Completed)</div>
				</div>
			</div>
			</div>
		</div>
		<div id="log" class="tab-pane fade ">
			<ul class="list-group">
				{% for log in logs  %}
					<li class="list-group-item list-group-item-success">{{log.activity}} {{log.project.proj_id}} {{log.proj_rev}} {{log.date}}</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	
	{% if step %}
	<p>
		<a href="{% url 'projects:Proceed' step%}">
			<button type="button" class="btn btn-primary" name="Submit">Next</button>
		</a>
	</p>
	{% endif %}
{% endblock content %}